### ISSUE TITLE
unmatched data type

### ISSUE THREAD

**Issue by JUNZHU-SEIS** [wayneweiqiang/PhaseNet#23]
I want to re-train the PhaseNet, by running

>>>python phasenet/train.py --mode=train --epochs=10 --format="numpy" --train_dir=dataset/waveform_train --train_list=dataset/train.csv --batch_size=20

I found error below:

Traceback (most recent call last):
  File "phasenet/train.py", line 233, in <module>
    main(args)
  File "phasenet/train.py", line 216, in main
    train_fn(args, data_reader, data_reader_valid)
  File "phasenet/train.py", line 103, in train_fn
    feed_dict={model.drop_rate: args.drop_rate, model.is_training: True})
  File "/home/as/anaconda3/envs/phasenet/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 968, in run
    run_metadata_ptr)
  File "/home/as/anaconda3/envs/phasenet/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1191, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/as/anaconda3/envs/phasenet/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1369, in _do_run
    run_metadata)
  File "/home/as/anaconda3/envs/phasenet/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 0-th value returned by pyfunc_0 is double, but expects float
	 [[{{node PyFunc}}]]
	 [[Input_Batch/IteratorGetNext]]

PS: Firstly I found the input data for new branch's training mode is different, more specifically, the npz format data has no "itp" key, "p_idx" instead. So I change the key in my training data to "p_idx" and "s_idx".

**Comment by wayneweiqiang** [comment]
Thanks for reporting this issue. I have broken it in a previous refactorization. I have fixed it in a new commit.

**Comment by JUNZHU-SEIS** [comment]
It works now, thank you
