### ISSUE TITLE
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

### ISSUE THREAD

**Issue by zhong-yy** [wayneweiqiang/PhaseNet#32]
**Description**

Hi, I got this error when I tried to follow the instruction in `example_batch_prediction.ipynb`

I used `conda env create -f env.yml` to create the **phasenet** environment.  Then I download the test data 
```bash
wget https://github.com/wayneweiqiang/PhaseNet/releases/download/test_data/test_data.zip
unzip test_data.zip
```
When I run the prediction,
```bash
python phasenet/predict.py --model=model/190703-214543 --data_list=test_data/npz.csv --data_dir=test_data/npz --format=numpy --plot_figure
```
the error occurred
```bash
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Traceback (most recent call last):
  File "phasenet/predict.py", line 12, in <module>
    import tensorflow as tf
  File "/home/yyzhong/anaconda3/envs/phasenet/lib/python3.7/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/yyzhong/anaconda3/envs/phasenet/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "/home/yyzhong/anaconda3/envs/phasenet/lib/python3.7/site-packages/tensorflow/python/eager/context.py", line 37, in <module>
    from tensorflow.python.client import pywrap_tf_session
  File "/home/yyzhong/anaconda3/envs/phasenet/lib/python3.7/site-packages/tensorflow/python/client/pywrap_tf_session.py", line 23, in <module>
    from tensorflow.python.client._pywrap_tf_session import *
ImportError: SystemError: <built-in method __contains__ of dict object at 0x7f511ca08320> returned a result with an error set
```
**System information**

- Ubuntu 20.04

**Versions of the packages in env.yml**

- python 3.7.11
- numpy 1.21.2
- scipy 1.7.1
- pandas 1.3.4
- scikit-learn 1.0.1
- tensorflow 2.6.0
- tqdm 4.62.3
- obspy 1.2.2
- uvicon 0.15.0
- fastapi 0.70.0
- kafka-python 2.0.2

**Comment by zhong-yy** [comment]
It may be due to incompatibility of numpy1.21 and tensorflow. 

I solved it by using lower versions of numpy and tensorflow.

  - python=3.7
  - numpy=1.18.5
  - pandas=1.1.3
  - scikit-learn=0.24.2
  - tensorflow=2.3.0
